# Generated by Django 5.1.13 on 2025-11-04 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(choices=[('Sega', 'Sega'), ('Sony', 'Sony'), ('Nintendo', 'Nintendo')], max_length=50)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(choices=[('Estados Unidos', 'Estados Unidos'), ('Francia', 'Francia'), ('China', 'China')], max_length=50)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.estudio')),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('ventas_estimadas', models.PositiveIntegerField(default=100000, null=True)),
                ('estudio_desarrollo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.estudio')),
                ('plataforma', models.ManyToManyField(related_name='videojuego_plataforma', to='examen.plataforma')),
            ],
        ),
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.DecimalField(decimal_places=2, default=1200.0, max_digits=7)),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.videojuego')),
            ],
        ),
    ]
