# Generated by Django 5.1.13 on 2025-11-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis',
            name='puntuacion',
            field=models.IntegerField(default=50, null=True),
        ),
    ]
