# Generated by Django 5.1.13 on 2025-11-04 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0002_alter_analisis_puntuacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojuego',
            name='plataforma',
        ),
        migrations.AddField(
            model_name='analisis',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analisis',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analisis',
            name='puntuacion',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='analisis',
            name='videojuego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='examen.videojuego'),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='fabricante',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sede',
            name='estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='examen.estudio'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='pais',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='estudio_desarrollo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videojuegos', to='examen.estudio'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='ventas_estimadas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VideojuegoPlataformas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plataformas_videojuegos', to='examen.plataforma')),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videojuego_plataformas', to='examen.videojuego')),
            ],
        ),
    ]
