# Generated by Django 5.1.13 on 2025-11-18 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0003_remove_videojuego_plataforma_analisis_comentario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad_estimada', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sede',
            name='estudio',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='estudio_desarrollo',
        ),
        migrations.RemoveField(
            model_name='videojuegoplataformas',
            name='videojuego',
        ),
        migrations.RemoveField(
            model_name='videojuegoplataformas',
            name='plataforma',
        ),
        migrations.RenameModel(
            old_name='Plataforma',
            new_name='Vacuna',
        ),
        migrations.CreateModel(
            name='AnimalVacunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_vacunas', to='examen.animal')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_vacunas', to='examen.vacuna')),
            ],
        ),
        migrations.RenameModel(
            old_name='Estudio',
            new_name='Refugio',
        ),
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('refugio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros', to='examen.refugio')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animales', to='examen.centro'),
        ),
        migrations.CreateModel(
            name='RevisionVeterinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion_salud', models.IntegerField()),
                ('veterinario', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='examen.animal')),
            ],
        ),
        migrations.DeleteModel(
            name='Analisis',
        ),
        migrations.DeleteModel(
            name='Sede',
        ),
        migrations.DeleteModel(
            name='Videojuego',
        ),
        migrations.DeleteModel(
            name='VideojuegoPlataformas',
        ),
    ]
